In [2]:
import pandas as pd
from io import StringIO

data = """Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
LP001,Male,Yes,0,Graduate,No,5849,0,128,360,1,Urban,Y
LP002,Female,No,1,Graduate,No,4583,1508,128,360,1,Rural,N
LP003,Male,Yes,0,Graduate,Yes,3000,0,66,360,1,Urban,Y
LP004,Male,Yes,0,Not Graduate,No,2583,2358,120,360,1,Urban,Y
LP005,Male,No,0,Graduate,No,6000,0,141,360,1,Urban,Y
LP006,Male,Yes,2,Graduate,Yes,5417,4196,267,360,1,Urban,Y
LP007,Female,No,0,Not Graduate,No,2333,1516,95,360,1,Rural,N
LP008,Male,Yes,3,Graduate,No,3036,2504,158,360,0,Semiurban,N
LP009,Male,Yes,2,Graduate,No,4000,1526,113,360,1,Semiurban,Y
LP010,Female,No,0,Graduate,No,3200,0,70,360,1,Urban,Y
LP011,Male,Yes,1,Graduate,No,4300,1800,120,360,1,Rural,Y
LP012,Female,No,0,Graduate,No,3500,0,100,360,1,Urban,Y
LP013,Male,Yes,0,Graduate,No,2700,1500,90,360,1,Rural,N
LP014,Male,Yes,2,Not Graduate,No,2900,1200,110,360,1,Semiurban,Y
LP015,Female,Yes,0,Graduate,No,5500,0,125,360,1,Urban,Y
LP016,Male,No,0,Graduate,Yes,3500,0,100,360,0,Rural,N
LP017,Male,Yes,1,Graduate,No,4500,2000,130,360,1,Semiurban,Y
LP018,Female,No,0,Not Graduate,No,2500,0,80,360,1,Rural,N
LP019,Male,Yes,3,Graduate,Yes,7000,3000,200,360,1,Urban,Y
LP020,Male,Yes,0,Graduate,No,5000,0,140,360,1,Urban,Y
LP021,Female,Yes,1,Graduate,No,4200,1200,115,360,1,Semiurban,Y
LP022,Male,No,2,Graduate,No,2800,1800,100,360,0,Rural,N
LP023,Male,Yes,0,Graduate,No,6200,0,160,360,1,Urban,Y
LP024,Female,No,0,Graduate,No,3100,0,90,360,1,Semiurban,Y
LP025,Male,Yes,1,Not Graduate,No,2600,1500,100,360,1,Rural,N
LP026,Male,Yes,2,Graduate,No,4800,2000,135,360,1,Urban,Y
LP027,Female,No,0,Graduate,Yes,3600,0,110,360,1,Semiurban,Y
LP028,Male,Yes,3,Graduate,No,3900,1800,125,360,1,Rural,Y
LP029,Male,No,0,Not Graduate,No,2400,0,75,360,0,Rural,N
LP030,Female,Yes,1,Graduate,No,5100,1000,130,360,1,Urban,Y
"""

df = pd.read_csv(StringIO(data))

ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

In [8]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001,Male,Yes,0,Graduate,No,5849,0,128,360,1,Urban,Y
1,LP002,Female,No,1,Graduate,No,4583,1508,128,360,1,Rural,N
2,LP003,Male,Yes,0,Graduate,Yes,3000,0,66,360,1,Urban,Y
3,LP004,Male,Yes,0,Not Graduate,No,2583,2358,120,360,1,Urban,Y
4,LP005,Male,No,0,Graduate,No,6000,0,141,360,1,Urban,Y

In [2]:
df.to_csv("loan_dataset.csv", index=False)

NameError: name 'df' is not defined

In [3]:
df = pd.read_csv("loan_dataset.csv")

In [11]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001,Male,Yes,0,Graduate,No,5849,0,128,360,1,Urban,Y
1,LP002,Female,No,1,Graduate,No,4583,1508,128,360,1,Rural,N
2,LP003,Male,Yes,0,Graduate,Yes,3000,0,66,360,1,Urban,Y
3,LP004,Male,Yes,0,Not Graduate,No,2583,2358,120,360,1,Urban,Y
4,LP005,Male,No,0,Graduate,No,6000,0,141,360,1,Urban,Y

In [12]:
df.tail()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
25,LP026,Male,Yes,2,Graduate,No,4800,2000,135,360,1,Urban,Y
26,LP027,Female,No,0,Graduate,Yes,3600,0,110,360,1,Semiurban,Y
27,LP028,Male,Yes,3,Graduate,No,3900,1800,125,360,1,Rural,Y
28,LP029,Male,No,0,Not Graduate,No,2400,0,75,360,0,Rural,N
29,LP030,Female,Yes,1,Graduate,No,5100,1000,130,360,1,Urban,Y

In [14]:
df.shape

(30, 13)

In [15]:
df.columns.tolist()

['Loan_ID',
 'Gender',
 'Married',
 'Dependents',
 'Education',
 'Self_Employed',
 'ApplicantIncome',
 'CoapplicantIncome',
 'LoanAmount',
 'Loan_Amount_Term',
 'Credit_History',
 'Property_Area',
 'Loan_Status']

In [16]:
df.dtypes

Loan_ID              object
Gender               object
Married              object
Dependents            int64
Education            object
Self_Employed        object
ApplicantIncome       int64
CoapplicantIncome     int64
LoanAmount            int64
Loan_Amount_Term      int64
Credit_History        int64
Property_Area        object
Loan_Status          object
dtype: object

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            30 non-null     object
 1   Gender             30 non-null     object
 2   Married            30 non-null     object
 3   Dependents         30 non-null     int64
 4   Education          30 non-null     object
 5   Self_Employed      30 non-null     object
 6   ApplicantIncome    30 non-null     int64
 7   CoapplicantIncome  30 non-null     int64
 8   LoanAmount         30 non-null     int64
 9   Loan_Amount_Term   30 non-null     int64
 10  Credit_History     30 non-null     int64
 11  Property_Area      30 non-null     object
 12  Loan_Status        30 non-null     object
dtypes: int64(6), object(7)
memory usage: 3.2+ KB

In [18]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [19]:
df.describe()

,Dependents,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,30.000000,30.000000,30.000000,30.000000,30.0,30.000000
mean,0.833333,4003.366667,1080.266667,120.700000,360.0,0.866667
std,1.053183,1300.295894,1120.780360,39.750211,0.0,0.345746
min,0.000000,2333.000000,0.000000,66.000000,360.0,0.000000
25%,0.000000,2925.000000,0.000000,100.000000,360.0,1.000000
50%,0.000000,3750.000000,1200.000000,117.500000,360.0,1.000000
75%,1.750000,4950.000000,1800.000000,130.000000,360.0,1.000000
max,3.000000,7000.000000,4196.000000,267.000000,360.0,1.000000

In [20]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001,Male,Yes,0,Graduate,No,5849,0,128,360,1,Urban,Y
1,LP002,Female,No,1,Graduate,No,4583,1508,128,360,1,Rural,N
2,LP003,Male,Yes,0,Graduate,Yes,3000,0,66,360,1,Urban,Y
3,LP004,Male,Yes,0,Not Graduate,No,2583,2358,120,360,1,Urban,Y
4,LP005,Male,No,0,Graduate,No,6000,0,141,360,1,Urban,Y

In [23]:
df["Loan_Status"].value_counts()

Loan_Status
Y    21
N     9
Name: count, dtype: int64

In [32]:
x = df.drop("Loan_Status",axis=1)
y = df['Loan_Status']

In [26]:
df['Gender'].value_counts()

Gender
Male      20
Female    10
Name: count, dtype: int64

In [27]:
df["Education"].value_counts()

Education
Graduate        24
Not Graduate     6
Name: count, dtype: int64

In [28]:
df["Property_Area"].value_counts()

Property_Area
Urban        13
Rural        10
Semiurban     7
Name: count, dtype: int64

In [33]:
df[df['ApplicantIncome']>5000]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001,Male,Yes,0,Graduate,No,5849,0,128,360,1,Urban,Y
4,LP005,Male,No,0,Graduate,No,6000,0,141,360,1,Urban,Y
5,LP006,Male,Yes,2,Graduate,Yes,5417,4196,267,360,1,Urban,Y
14,LP015,Female,Yes,0,Graduate,No,5500,0,125,360,1,Urban,Y
18,LP019,Male,Yes,3,Graduate,Yes,7000,3000,200,360,1,Urban,Y
22,LP023,Male,Yes,0,Graduate,No,6200,0,160,360,1,Urban,Y
29,LP030,Female,Yes,1,Graduate,No,5100,1000,130,360,1,Urban,Y

In [34]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001,Male,Yes,0,Graduate,No,5849,0,128,360,1,Urban,Y
1,LP002,Female,No,1,Graduate,No,4583,1508,128,360,1,Rural,N
2,LP003,Male,Yes,0,Graduate,Yes,3000,0,66,360,1,Urban,Y
3,LP004,Male,Yes,0,Not Graduate,No,2583,2358,120,360,1,Urban,Y
4,LP005,Male,No,0,Graduate,No,6000,0,141,360,1,Urban,Y

In [35]:
df[df["Loan_Status"]=="Y"]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001,Male,Yes,0,Graduate,No,5849,0,128,360,1,Urban,Y
2,LP003,Male,Yes,0,Graduate,Yes,3000,0,66,360,1,Urban,Y
3,LP004,Male,Yes,0,Not Graduate,No,2583,2358,120,360,1,Urban,Y
4,LP005,Male,No,0,Graduate,No,6000,0,141,360,1,Urban,Y
5,LP006,Male,Yes,2,Graduate,Yes,5417,4196,267,360,1,Urban,Y
8,LP009,Male,Yes,2,Graduate,No,4000,1526,113,360,1,Semiurban,Y
9,LP010,Female,No,0,Graduate,No,3200,0,70,360,1,Urban,Y
10,LP011,Male,Yes,1,Graduate,No,4300,1800,120,360,1,Rural,Y
11,LP012,Female,No,0,Graduate,No,3500,0,100,360,1,Urban,Y
13,LP014,Male,Yes,2,Not Graduate,No,2900,1200,110,360,1,Semiurban,Y
14,LP015,Female,Yes,0,Graduate,No,5500,0,125,360,1,Urban,Y
16,LP017,Male,Yes,1,Graduate,No,4500,2000,130,360,1,Semiurban,Y
18,LP019,Male,Yes,3,Graduate,Yes,7000,3000,200,360,1,Urban,Y
19,LP020,Male,Yes,0,Graduate,No,5000,0,140,360,1,Urban,Y
20,LP021,Female,Yes,1,Graduate,No,4200,1200,115,360,1,Semiurban,Y
22,LP023,Male,Yes,0,Graduate,No,6200,0,160,360,1,Urban,Y
23,LP024,Female,No,0,Graduate,No,3100,0,90,360,1,Semiurban,Y
25,LP026,Male,Yes,2,Graduate,No,4800,2000,135,360,1,Urban,Y
26,LP027,Female,No,0,Graduate,Yes,3600,0,110,360,1,Semiurban,Y
27,LP028,Male,Yes,3,Graduate,No,3900,1800,125,360,1,Rural,Y
29,LP030,Female,Yes,1,Graduate,No,5100,1000,130,360,1,Urban,Y

In [36]:
df[df["Education"] == "Graduate"]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001,Male,Yes,0,Graduate,No,5849,0,128,360,1,Urban,Y
1,LP002,Female,No,1,Graduate,No,4583,1508,128,360,1,Rural,N
2,LP003,Male,Yes,0,Graduate,Yes,3000,0,66,360,1,Urban,Y
4,LP005,Male,No,0,Graduate,No,6000,0,141,360,1,Urban,Y
5,LP006,Male,Yes,2,Graduate,Yes,5417,4196,267,360,1,Urban,Y
7,LP008,Male,Yes,3,Graduate,No,3036,2504,158,360,0,Semiurban,N
8,LP009,Male,Yes,2,Graduate,No,4000,1526,113,360,1,Semiurban,Y
9,LP010,Female,No,0,Graduate,No,3200,0,70,360,1,Urban,Y
10,LP011,Male,Yes,1,Graduate,No,4300,1800,120,360,1,Rural,Y
11,LP012,Female,No,0,Graduate,No,3500,0,100,360,1,Urban,Y
12,LP013,Male,Yes,0,Graduate,No,2700,1500,90,360,1,Rural,N
14,LP015,Female,Yes,0,Graduate,No,5500,0,125,360,1,Urban,Y
15,LP016,Male,No,0,Graduate,Yes,3500,0,100,360,0,Rural,N
16,LP017,Male,Yes,1,Graduate,No,4500,2000,130,360,1,Semiurban,Y
18,LP019,Male,Yes,3,Graduate,Yes,7000,3000,200,360,1,Urban,Y
19,LP020,Male,Yes,0,Graduate,No,5000,0,140,360,1,Urban,Y
20,LP021,Female,Yes,1,Graduate,No,4200,1200,115,360,1,Semiurban,Y
21,LP022,Male,No,2,Graduate,No,2800,1800,100,360,0,Rural,N
22,LP023,Male,Yes,0,Graduate,No,6200,0,160,360,1,Urban,Y
23,LP024,Female,No,0,Graduate,No,3100,0,90,360,1,Semiurban,Y
25,LP026,Male,Yes,2,Graduate,No,4800,2000,135,360,1,Urban,Y
26,LP027,Female,No,0,Graduate,Yes,3600,0,110,360,1,Semiurban,Y
27,LP028,Male,Yes,3,Graduate,No,3900,1800,125,360,1,Rural,Y
29,LP030,Female,Yes,1,Graduate,No,5100,1000,130,360,1,Urban,Y

TIME TO PRACTICE

In [38]:
df.head(5)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001,Male,Yes,0,Graduate,No,5849,0,128,360,1,Urban,Y
1,LP002,Female,No,1,Graduate,No,4583,1508,128,360,1,Rural,N
2,LP003,Male,Yes,0,Graduate,Yes,3000,0,66,360,1,Urban,Y
3,LP004,Male,Yes,0,Not Graduate,No,2583,2358,120,360,1,Urban,Y
4,LP005,Male,No,0,Graduate,No,6000,0,141,360,1,Urban,Y

In [39]:
df.tail(5)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
25,LP026,Male,Yes,2,Graduate,No,4800,2000,135,360,1,Urban,Y
26,LP027,Female,No,0,Graduate,Yes,3600,0,110,360,1,Semiurban,Y
27,LP028,Male,Yes,3,Graduate,No,3900,1800,125,360,1,Rural,Y
28,LP029,Male,No,0,Not Graduate,No,2400,0,75,360,0,Rural,N
29,LP030,Female,Yes,1,Graduate,No,5100,1000,130,360,1,Urban,Y

In [41]:
df.shape

(30, 13)

In [43]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [44]:
df.dtypes

Loan_ID              object
Gender               object
Married              object
Dependents            int64
Education            object
Self_Employed        object
ApplicantIncome       int64
CoapplicantIncome     int64
LoanAmount            int64
Loan_Amount_Term      int64
Credit_History        int64
Property_Area        object
Loan_Status          object
dtype: object

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            30 non-null     object
 1   Gender             30 non-null     object
 2   Married            30 non-null     object
 3   Dependents         30 non-null     int64
 4   Education          30 non-null     object
 5   Self_Employed      30 non-null     object
 6   ApplicantIncome    30 non-null     int64
 7   CoapplicantIncome  30 non-null     int64
 8   LoanAmount         30 non-null     int64
 9   Loan_Amount_Term   30 non-null     int64
 10  Credit_History     30 non-null     int64
 11  Property_Area      30 non-null     object
 12  Loan_Status        30 non-null     object
dtypes: int64(6), object(7)
memory usage: 3.2+ KB

In [47]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [49]:
df.duplicated().sum()

0

In [54]:
df['Loan_Status'].value_counts()

Loan_Status
Y    21
N     9
Name: count, dtype: int64

In [55]:
df['Gender'].value_counts()

Gender
Male      20
Female    10
Name: count, dtype: int64

In [56]:
df['Education'].value_counts()

Education
Graduate        24
Not Graduate     6
Name: count, dtype: int64

In [57]:
df[df['ApplicantIncome']>5000]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001,Male,Yes,0,Graduate,No,5849,0,128,360,1,Urban,Y
4,LP005,Male,No,0,Graduate,No,6000,0,141,360,1,Urban,Y
5,LP006,Male,Yes,2,Graduate,Yes,5417,4196,267,360,1,Urban,Y
14,LP015,Female,Yes,0,Graduate,No,5500,0,125,360,1,Urban,Y
18,LP019,Male,Yes,3,Graduate,Yes,7000,3000,200,360,1,Urban,Y
22,LP023,Male,Yes,0,Graduate,No,6200,0,160,360,1,Urban,Y
29,LP030,Female,Yes,1,Graduate,No,5100,1000,130,360,1,Urban,Y

In [58]:
df[df['LoanAmount']>150]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
5,LP006,Male,Yes,2,Graduate,Yes,5417,4196,267,360,1,Urban,Y
7,LP008,Male,Yes,3,Graduate,No,3036,2504,158,360,0,Semiurban,N
18,LP019,Male,Yes,3,Graduate,Yes,7000,3000,200,360,1,Urban,Y
22,LP023,Male,Yes,0,Graduate,No,6200,0,160,360,1,Urban,Y

In [64]:
df[df['Loan_Status']=="Y" ].value_counts()

Loan_ID  Gender  Married  Dependents  Education     Self_Employed  ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  Property_Area  Loan_Status
LP001    Male    Yes      0           Graduate      No             5849             0                  128         360               1               Urban          Y              1
LP017    Male    Yes      1           Graduate      No             4500             2000               130         360               1               Semiurban      Y              1
LP028    Male    Yes      3           Graduate      No             3900             1800               125         360               1               Rural          Y              1
LP027    Female  No       0           Graduate      Yes            3600             0                  110         360               1               Semiurban      Y              1
LP026    Male    Yes      2           Graduate      No             4800             2000               135         360               1               Urban          Y              1
LP024    Female  No       0           Graduate      No             3100             0                  90          360               1               Semiurban      Y              1
LP023    Male    Yes      0           Graduate      No             6200             0                  160         360               1               Urban          Y              1
LP021    Female  Yes      1           Graduate      No             4200             1200               115         360               1               Semiurban      Y              1
LP020    Male    Yes      0           Graduate      No             5000             0                  140         360               1               Urban          Y              1
LP019    Male    Yes      3           Graduate      Yes            7000             3000               200         360               1               Urban          Y              1
LP015    Female  Yes      0           Graduate      No             5500             0                  125         360               1               Urban          Y              1
LP003    Male    Yes      0           Graduate      Yes            3000             0                  66          360               1               Urban          Y              1
LP014    Male    Yes      2           Not Graduate  No             2900             1200               110         360               1               Semiurban      Y              1
LP012    Female  No       0           Graduate      No             3500             0                  100         360               1               Urban          Y              1
LP011    Male    Yes      1           Graduate      No             4300             1800               120         360               1               Rural          Y              1
LP010    Female  No       0           Graduate      No             3200             0                  70          360               1               Urban          Y              1
LP009    Male    Yes      2           Graduate      No             4000             1526               113         360               1               Semiurban      Y              1
LP006    Male    Yes      2           Graduate      Yes            5417             4196               267         360               1               Urban          Y              1
LP005    Male    No       0           Graduate      No             6000             0                  141         360               1               Urban          Y              1
LP004    Male    Yes      0           Not Graduate  No             2583             2358               120         360               1               Urban          Y              1
LP030    Female  Yes      1           Graduate      No             5100             1000               130         360               1               Urban          Y              1
Name: count, dtype: int64

In [68]:
df['Property_Area']=='Urban'

0      True
1     False
2      True
3      True
4      True
5      True
6     False
7     False
8     False
9      True
10    False
11     True
12    False
13    False
14     True
15    False
16    False
17    False
18     True
19     True
20    False
21    False
22     True
23    False
24    False
25     True
26    False
27    False
28    False
29     True
Name: Property_Area, dtype: bool

In [1]:
import pandas as pd 
import numpy as np

ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

In [4]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001,Male,Yes,0,Graduate,No,5849,0,128,360,1,Urban,Y
1,LP002,Female,No,1,Graduate,No,4583,1508,128,360,1,Rural,N
2,LP003,Male,Yes,0,Graduate,Yes,3000,0,66,360,1,Urban,Y
3,LP004,Male,Yes,0,Not Graduate,No,2583,2358,120,360,1,Urban,Y
4,LP005,Male,No,0,Graduate,No,6000,0,141,360,1,Urban,Y

    NUMPY + BASIC EDA

In [5]:
numeric_cols = [
    "ApplicantIncome",
    "CoapplicantIncome",
    "LoanAmount",
    "Loan_Amount_Term",
    "Credit_History"
]

df[numeric_cols]

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
0,5849,0,128,360,1
1,4583,1508,128,360,1
2,3000,0,66,360,1
3,2583,2358,120,360,1
4,6000,0,141,360,1
5,5417,4196,267,360,1
6,2333,1516,95,360,1
7,3036,2504,158,360,0
8,4000,1526,113,360,1
9,3200,0,70,360,1
10,4300,1800,120,360,1
11,3500,0,100,360,1
12,2700,1500,90,360,1
13,2900,1200,110,360,1
14,5500,0,125,360,1
15,3500,0,100,360,0
16,4500,2000,130,360,1
17,2500,0,80,360,1
18,7000,3000,200,360,1
19,5000,0,140,360,1
20,4200,1200,115,360,1
21,2800,1800,100,360,0
22,6200,0,160,360,1
23,3100,0,90,360,1
24,2600,1500,100,360,1
25,4800,2000,135,360,1
26,3600,0,110,360,1
27,3900,1800,125,360,1
28,2400,0,75,360,0
29,5100,1000,130,360,1

NumPy = Python library for working efficiently with numbers and arrays.

In [7]:
import numpy as np

In [8]:
income = np.array(df['ApplicantIncome'])
income

array([5849, 4583, 3000, 2583, 6000, 5417, 2333, 3036, 4000, 3200, 4300,
       3500, 2700, 2900, 5500, 3500, 4500, 2500, 7000, 5000, 4200, 2800,
       6200, 3100, 2600, 4800, 3600, 3900, 2400, 5100], dtype=int64)

In [9]:
np.mean(income)

4003.366666666667

In [10]:
np.min(income)

2333

In [11]:
np.max(income)

7000

In [12]:
np.median(income)

3750.0

In [15]:
df['Loan_Status'].value_counts(normalize=True)*100

Loan_Status
Y    70.0
N    30.0
Name: proportion, dtype: float64

In [16]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001,Male,Yes,0,Graduate,No,5849,0,128,360,1,Urban,Y
1,LP002,Female,No,1,Graduate,No,4583,1508,128,360,1,Rural,N
2,LP003,Male,Yes,0,Graduate,Yes,3000,0,66,360,1,Urban,Y
3,LP004,Male,Yes,0,Not Graduate,No,2583,2358,120,360,1,Urban,Y
4,LP005,Male,No,0,Graduate,No,6000,0,141,360,1,Urban,Y

In [4]:
df.groupby("Loan_Status")["ApplicantIncome"].mean()

Loan_Status
N    2939.111111
Y    4459.476190
Name: ApplicantIncome, dtype: float64

In [21]:
df.groupby('Education')['ApplicantIncome'].max()

Education
Graduate        7000
Not Graduate    2900
Name: ApplicantIncome, dtype: int64

In [22]:
df.groupby('Loan_Status')['LoanAmount'].mean()

Loan_Status
N    102.888889
Y    128.333333
Name: LoanAmount, dtype: float64

In [20]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001,Male,Yes,0,Graduate,No,5849,0,128,360,1,Urban,Y
1,LP002,Female,No,1,Graduate,No,4583,1508,128,360,1,Rural,N
2,LP003,Male,Yes,0,Graduate,Yes,3000,0,66,360,1,Urban,Y
3,LP004,Male,Yes,0,Not Graduate,No,2583,2358,120,360,1,Urban,Y
4,LP005,Male,No,0,Graduate,No,6000,0,141,360,1,Urban,Y

In [6]:
pd.crosstab(df["Education"], df["Loan_Status"])

Loan_Status   N   Y
Education
Graduate      5  19
Not Graduate  4   2

In [8]:
pd.crosstab(df["Property_Area"],df["Loan_Status"])

Loan_Status    N   Y
Property_Area
Rural          8   2
Semiurban      1   6
Urban          0  13