In [1]:
import pandas as pd 
import numpy as np 
from io import StringIO

In [2]:
df = pd.read_csv('S:\Github\machine learinng\loan_dataset.csv')

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
C:\Users\DELL\AppData\Local\Temp\ipykernel_4788\3651438435.py:1: SyntaxWarning: invalid escape sequence '\G'
  df = pd.read_csv('S:\Github\machine learinng\loan_dataset.csv')

In [3]:
df.head(2)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001,Male,Yes,0,Graduate,No,5849,0,128,360,1,Urban,Y
1,LP002,Female,No,1,Graduate,No,4583,1508,128,360,1,Rural,N

In [8]:
df['ApplicantIncome'].mean()

4003.366666666667

In [9]:
df["ApplicantIncome"].median()

3750.0

In [10]:
df["LoanAmount"].max()

267

missing values

In [11]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

This code is use to fill values through median --its just an example

In [ ]:
df["LoanAmount"].fillna(df["LoanAmount"].median(),inplace=True)

Step 2 — Categorical Data

Our ML model can't directly understand:

Gender
Male
Female

or:

Education
Graduate
Not Graduate

We need to convert them into numbers.

For example:

Graduate       → 1
Not Graduate   → 0

This is called encoding.

You'll learn:

Label Encoding
One-Hot Encoding

pd.get_dummies()

Train/Test Split

In [18]:
x = df.drop("Loan_Status",axis=1)
y = df["Loan_Status"]

In [17]:
import numpy as np

print(np.__version__)

2.4.6

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

NameError: name 'X' is not defined

In [22]:
df_ml = df.copy()

In [23]:
df_ml.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001,Male,Yes,0,Graduate,No,5849,0,128,360,1,Urban,Y
1,LP002,Female,No,1,Graduate,No,4583,1508,128,360,1,Rural,N
2,LP003,Male,Yes,0,Graduate,Yes,3000,0,66,360,1,Urban,Y
3,LP004,Male,Yes,0,Not Graduate,No,2583,2358,120,360,1,Urban,Y
4,LP005,Male,No,0,Graduate,No,6000,0,141,360,1,Urban,Y

In [24]:
X = df_ml.drop("Loan_Status", axis=1)

In [25]:
y = df_ml["Loan_Status"]

In [26]:
print("X:")
print(X.head())

print("\ny:")
print(y.head())

X:
  Loan_ID  Gender Married  Dependents     Education Self_Employed  \
0   LP001    Male     Yes           0      Graduate            No
1   LP002  Female      No           1      Graduate            No
2   LP003    Male     Yes           0      Graduate           Yes
3   LP004    Male     Yes           0  Not Graduate            No
4   LP005    Male      No           0      Graduate            No

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                  0         128               360
1             4583               1508         128               360
2             3000                  0          66               360
3             2583               2358         120               360
4             6000                  0         141               360

   Credit_History Property_Area
0               1         Urban
1               1         Rural
2               1         Urban
3               1         Urban
4               1         Urban

y:
0    Y
1    N
2    Y
3    Y
4    Y
Name: Loan_Status, dtype: object

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [21]:
print("X shape:", X.shape)
print("y shape:", y.shape)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X shape: (30, 12)
y shape: (30,)
X_train shape: (24, 12)
X_test shape: (6, 12)
y_train shape: (24,)
y_test shape: (6,)

In [28]:
print('x:')
print(x.head())
print('\ny:')
print(y.head())

x:
  Loan_ID  Gender Married  Dependents     Education Self_Employed  \
0   LP001    Male     Yes           0      Graduate            No
1   LP002  Female      No           1      Graduate            No
2   LP003    Male     Yes           0      Graduate           Yes
3   LP004    Male     Yes           0  Not Graduate            No
4   LP005    Male      No           0      Graduate            No

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                  0         128               360
1             4583               1508         128               360
2             3000                  0          66               360
3             2583               2358         120               360
4             6000                  0         141               360

   Credit_History Property_Area
0               1         Urban
1               1         Rural
2               1         Urban
3               1         Urban
4               1         Urban

y:
0    Y
1    N
2    Y
3    Y
4    Y
Name: Loan_Status, dtype: object

In [29]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(
    x , y , test_size=0.2 , random_state=42
)